import { Toaster } from "@/components/ui/sonner";
import "./globals.css";


export const metadata = {
  title: "Price Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>  
        <Toaster richColors />
        {children}
      </body>
      
    </html>
  );
}
